-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  type text NOT NULL DEFAULT 'general'::text,
  is_published boolean NOT NULL DEFAULT false,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  CONSTRAINT announcements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  action_type text NOT NULL,
  resource_type text,
  resource_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address text,
  user_agent text,
  status text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.card_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  card_id uuid NOT NULL,
  user_id uuid NOT NULL,
  transaction_type text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'USD'::text,
  previous_balance numeric,
  new_balance numeric,
  payscribe_transaction_id text UNIQUE,
  payscribe_reference text,
  status text NOT NULL DEFAULT 'pending'::text,
  description text,
  failure_reason text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_at timestamp with time zone,
  CONSTRAINT card_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT card_transactions_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.payscribe_cards(id),
  CONSTRAINT card_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info'::text,
  category text NOT NULL DEFAULT 'general'::text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  related_id uuid,
  related_type text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trans_id character varying NOT NULL UNIQUE,
  ref uuid NOT NULL,
  amount numeric NOT NULL,
  fee numeric DEFAULT 0,
  total numeric NOT NULL,
  currency character varying DEFAULT 'NGN'::character varying,
  bank_code character varying NOT NULL,
  bank_name character varying,
  account_number character varying NOT NULL,
  account_name character varying NOT NULL,
  narration text,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT payouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payscribe_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  payscribe_card_id text NOT NULL UNIQUE,
  payscribe_transaction_id text,
  card_type text NOT NULL DEFAULT 'virtual'::text CHECK (card_type = ANY (ARRAY['virtual'::text, 'physical'::text])),
  brand text NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  first_six text NOT NULL,
  last_four text NOT NULL,
  masked_card text,
  card_number text,
  expiry text,
  cvv text,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0::numeric),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'terminated'::text, 'blocked'::text])),
  billing_address jsonb,
  payscribe_response jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payscribe_cards_pkey PRIMARY KEY (id),
  CONSTRAINT payscribe_cards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payscribe_networks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_code text NOT NULL,
  network_code text NOT NULL,
  network_name text NOT NULL,
  network_type text NOT NULL,
  is_active boolean DEFAULT true,
  icon_url text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payscribe_networks_pkey PRIMARY KEY (id),
  CONSTRAINT payscribe_networks_service_code_fkey FOREIGN KEY (service_code) REFERENCES public.payscribe_services(service_code)
);
CREATE TABLE public.payscribe_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_code text NOT NULL,
  network_id uuid NOT NULL,
  plan_id text NOT NULL,
  plan_name text NOT NULL,
  plan_code text,
  price numeric NOT NULL CHECK (price > 0::numeric),
  currency text NOT NULL DEFAULT 'NGN'::text,
  plan_type text,
  duration text,
  data_volume text,
  is_active boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payscribe_plans_pkey PRIMARY KEY (id),
  CONSTRAINT payscribe_plans_service_code_fkey FOREIGN KEY (service_code) REFERENCES public.payscribe_services(service_code),
  CONSTRAINT payscribe_plans_network_id_fkey FOREIGN KEY (network_id) REFERENCES public.payscribe_networks(id)
);
CREATE TABLE public.payscribe_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_code text NOT NULL UNIQUE,
  service_name text NOT NULL,
  service_description text,
  is_active boolean DEFAULT true,
  icon_url text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  last_synced_at timestamp with time zone,
  CONSTRAINT payscribe_services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payscribe_virtual_account_banks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_code text NOT NULL UNIQUE,
  bank_name text NOT NULL,
  bank_description text,
  is_active boolean DEFAULT true,
  supports_sandbox boolean DEFAULT true,
  supports_live boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payscribe_virtual_account_banks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username text UNIQUE,
  email text NOT NULL UNIQUE CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$'::text),
  mobile text UNIQUE CHECK (mobile IS NULL OR mobile ~ '^\+?[0-9]{10,15}$'::text),
  password_hash text NOT NULL,
  avatar_url text,
  first_name text,
  last_name text,
  is_merchant boolean DEFAULT false,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  mobile_verified boolean DEFAULT false,
  hashed_pin text,
  pin_salt text,
  biometric_enabled boolean DEFAULT false,
  last_login timestamp with time zone,
  login_attempts integer DEFAULT 0,
  locked_until timestamp with time zone,
  payscribe_customer_id text UNIQUE,
  payscribe_virtual_account_number text,
  payscribe_virtual_account_bank text,
  payscribe_virtual_account_ref text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  payscribe_tier integer DEFAULT 0,
  date_of_birth date,
  address_street text,
  address_city text,
  address_state text,
  address_country text,
  address_postal_code text,
  identification_type text,
  identification_number text,
  identification_photo_url text,
  identity_type text,
  identity_number text,
  identity_country text,
  identity_document_url text,
  photo_url text,
  kyc_verified boolean DEFAULT false,
  kyc_verified_at timestamp with time zone,
  payscribe_virtual_accounts jsonb,
  wallet_balance numeric DEFAULT 0,
  card_balance numeric DEFAULT 0,
  locked_balance numeric DEFAULT 0,
  balance_updated_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referral_bonuses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tier integer NOT NULL,
  bonus_type text NOT NULL DEFAULT 'data_2gb'::text,
  bonus_amount numeric NOT NULL DEFAULT 2,
  bonus_unit text NOT NULL DEFAULT 'GB'::text,
  is_claimed boolean NOT NULL DEFAULT false,
  claimed_at timestamp with time zone,
  is_redeemed boolean NOT NULL DEFAULT false,
  redeemed_at timestamp with time zone,
  redemption_transaction_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT referral_bonuses_pkey PRIMARY KEY (id),
  CONSTRAINT referral_bonuses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT referral_bonuses_transaction_id_fkey FOREIGN KEY (redemption_transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.referral_code_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referred_user_id uuid NOT NULL,
  referral_code text NOT NULL,
  used_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT referral_code_usage_pkey PRIMARY KEY (id),
  CONSTRAINT referral_code_usage_referrer_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id),
  CONSTRAINT referral_code_usage_referred_fkey FOREIGN KEY (referred_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.referral_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_id uuid NOT NULL,
  referred_user_id uuid NOT NULL,
  referral_code_used text NOT NULL,
  signup_completed boolean NOT NULL DEFAULT true,
  kyc_completed boolean NOT NULL DEFAULT false,
  kyc_completed_at timestamp with time zone,
  wallet_funded boolean NOT NULL DEFAULT false,
  wallet_funded_at timestamp with time zone,
  first_transaction_completed boolean NOT NULL DEFAULT false,
  first_transaction_at timestamp with time zone,
  is_counted boolean NOT NULL DEFAULT false,
  counted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT referral_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT referral_tracking_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id),
  CONSTRAINT referral_tracking_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  referral_code text NOT NULL UNIQUE,
  referrer_id uuid,
  current_tier integer NOT NULL DEFAULT 1,
  max_tier_reached integer NOT NULL DEFAULT 0,
  badge_name text NOT NULL DEFAULT 'Awakening'::text,
  total_referred integer NOT NULL DEFAULT 0,
  completed_referrals integer NOT NULL DEFAULT 0,
  tier_1_completed boolean NOT NULL DEFAULT false,
  tier_2_completed boolean NOT NULL DEFAULT false,
  tier_3_completed boolean NOT NULL DEFAULT false,
  tier_4_completed boolean NOT NULL DEFAULT false,
  tier_5_completed boolean NOT NULL DEFAULT false,
  tier_6_completed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.reserved_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  account_reference text NOT NULL UNIQUE,
  account_number text NOT NULL,
  account_name text NOT NULL,
  bank_name text,
  bank_code text,
  currency_code text DEFAULT 'NGN'::text,
  reservation_reference text,
  contract_code text,
  reserved_account_type text,
  status text DEFAULT 'active'::text,
  accounts jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT reserved_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT reserved_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  transaction_reference text NOT NULL UNIQUE,
  payscribe_reference text UNIQUE,
  transaction_type text NOT NULL,
  service_type text,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'NGN'::text,
  network_code text,
  plan_id text,
  provider_code text,
  recipient text,
  status text NOT NULL DEFAULT 'pending'::text,
  failure_reason text,
  metadata jsonb,
  virtual_account_reference text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallet_funding_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  event_reference text NOT NULL UNIQUE,
  payscribe_reference text NOT NULL,
  virtual_account_reference text,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'NGN'::text,
  event_type text NOT NULL DEFAULT 'credit'::text,
  event_status text NOT NULL DEFAULT 'pending'::text,
  previous_balance numeric,
  new_balance numeric,
  webhook_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_at timestamp with time zone,
  CONSTRAINT wallet_funding_events_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_funding_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0::numeric),
  locked_balance numeric NOT NULL DEFAULT 0 CHECK (locked_balance >= 0::numeric),
  total_funded numeric NOT NULL DEFAULT 0,
  total_spent numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'NGN'::text,
  last_balance_sync timestamp with time zone,
  last_sync_reference text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT wallets_pkey PRIMARY KEY (id),
  CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);